name: Feature Request
description: Suggest a new feature or enhancement for EVE Tools
title: "[FEATURE] "
labels: ["enhancement", "status: triage"]
assignees: []

body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module?
      options:
        - Authentication Module
        - Notification Module
        - General/Core
        - New Module
        - Not sure
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: "This feature would solve..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: How should this work?
      placeholder: "It should work by..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Other solutions considered?
      placeholder: "I've considered..."

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: Please confirm
      options:
        - label: I searched existing issues
          required: true
        - label: This aligns with EVE Tools goals
          required: true